package com.zylear.j2eelab.hook;

/**
 * Created by xiezongyu on 2018/11/29.
 */
public class CodeString {

    public static String string = "\n" +
            "rm -rf /data/data/com.chaozhuo.texteditor.phoenixos\n" +
            "rm -rf /data/data/com.chaozhuo.browser.x86\n" +
            "rm -rf /data/data/com.chaozhuo.feedback\n" +
            "rm -rf /data/data/com.chaozhuo.novicehelp\n" +
            "rm -rf /data/data/com.chaozhuo.setupwizard\n" +
            "rm -rf /data/data/com.chaozhuo.update\n" +
            "rm -rf /data/data/com.chaozhuo.voicerecorder\n" +
            "rm -rf /data/data/com.chaozhuo.recommendedapp\n" +
            "rm -rf /data/data/com.chaozhuo.phoenixonelauncher.x86\n" +
            "rm -rf /data/data/com.google.android.gms\n" +
            "rm -rf /data/data/com.google.android.gms.setup\n" +
            "rm -rf /data/data/com.android.vending\n" +
            "rm -rf /data/data/com.android.email\n" +
            "rm -rf /data/dalvik-cache/x86/system@app@CZFeedback@CZFeedback.apk@classes.art\n" +
            "rm -rf /data/dalvik-cache/x86/system@app@CZFeedback@CZFeedback.apk@classes.dex\n" +
            "rm -rf /data/dalvik-cache/x86/system@app@CZTextEditor@CZTextEditor.apk@classes.dex\n" +
            "rm -rf /data/dalvik-cache/x86/system@app@CZVoiceRecorder@CZVoiceRecorder.apk@classes.art\n" +
            "rm -rf /data/dalvik-cache/x86/system@app@CZVoiceRecorder@CZVoiceRecorder.apk@classes.dex\n" +
            "rm -rf /data/dalvik-cache/x86/system@app@FileManager@FileManager.apk@classes.dex\n" +
            "rm -rf /data/dalvik-cache/x86/system@priv-app@CZSetupWizard@CZSetupWizard.apk@classes.art\n" +
            "rm -rf /data/dalvik-cache/x86/system@priv-app@CZSetupWizard@CZSetupWizard.apk@classes.dex\n" +
            "rm -rf /data/dalvik-cache/x86_64/system@app@CZRecommended@CZRecommended.apk@classes.dex\n" +
            "rm -rf /data/dalvik-cache/x86_64/system@app@Email@Email.apk@classes.dex\n" +
            "rm -rf /data/dalvik-cache/x86_64/system@app@PhoenixOneForx86@PhoenixOneForx86.apk@classes.dex\n" +
            "rm -rf /data/dalvik-cache/x86_64/system@priv-app@CZStatisticsProvider@CZStatisticsProvider.apk@classes.dex\n" +
            "rm -rf /data/dalvik-cache/x86_64/system@priv-app@CZSystemUpdate@CZSystemUpdate.apk@classes.dex\n" +
            "rm -rf /data/dalvik-cache/x86_64/system@priv-app@GmsCore@GmsCore.apk@classes.dex\n" +
            "rm -rf /data/dalvik-cache/x86_64/system@priv-app@GmsCoreSetup@GmsCoreSetup.apk@classes.dex\n" +
            "rm -rf /data/dalvik-cache/x86_64/system@priv-app@Phonesky@Phonesky.apk@classes.dex\n" +
            "rm -rf /data/dalvik-cache/x86/system@app@CZFeedback@CZFeedback.apk@classes.art\n" +
            "rm -rf /data/dalvik-cache/x86/system@app@CZFeedback@CZFeedback.apk@classes.dex\n" +
            "rm -rf /data/dalvik-cache/x86/system@app@CZTextEditor@CZTextEditor.apk@classes.art\n" +
            "rm -rf /data/dalvik-cache/x86/system@app@CZTextEditor@CZTextEditor.apk@classes.dex\n" +
            "rm -rf /data/dalvik-cache/x86/system@app@CZVoiceRecorder@CZVoiceRecorder.apk@classes.art\n" +
            "rm -rf /data/dalvik-cache/x86/system@app@CZVoiceRecorder@CZVoiceRecorder.apk@classes.dex\n" +
            "rm -rf /data/dalvik-cache/x86/system@app@FileManager@FileManager.apk@classes.art\n" +
            "rm -rf /data/dalvik-cache/x86/system@app@FileManager@FileManager.apk@classes.dex\n" +
            "rm -rf /data/dalvik-cache/x86/system@app@StardustBrowser_pad@StardustBrowser_pad.apk@classes.art\n" +
            "rm -rf /data/dalvik-cache/x86/system@priv-app@CZSetupWizard@CZSetupWizard.apk@classes.art\n" +
            "rm -rf /data/dalvik-cache/x86/system@priv-app@CZSetupWizard@CZSetupWizard.apk@classes.dex\n" +
            "rm -rf /data/dalvik-cache/x86_64/system@app@CZRecommended@CZRecommended.apk@classes.art\n" +
            "rm -rf /data/dalvik-cache/x86_64/system@app@CZRecommended@CZRecommended.apk@classes.dex\n" +
            "rm -rf /data/dalvik-cache/x86_64/system@app@Email@Email.apk@classes.art\n" +
            "rm -rf /data/dalvik-cache/x86_64/system@app@Email@Email.apk@classes.dex\n" +
            "rm -rf /data/dalvik-cache/x86_64/system@app@PhoenixOneForx86@PhoenixOneForx86.apk@classes.art\n" +
            "rm -rf /data/dalvik-cache/x86_64/system@app@PhoenixOneForx86@PhoenixOneForx86.apk@classes.dex\n" +
            "rm -rf /data/dalvik-cache/x86_64/system@priv-app@CZNoviceHelp@CZNoviceHelp.apk@classes.art\n" +
            "rm -rf /data/dalvik-cache/x86_64/system@priv-app@CZNoviceHelp@CZNoviceHelp.apk@classes.dexCZNoviceHelp\n" +
            "rm -rf /data/dalvik-cache/x86_64/system@priv-app@CZStatisticsProvider@CZStatisticsProvider.apk@classes.art\n" +
            "rm -rf /data/dalvik-cache/x86_64/system@priv-app@CZStatisticsProvider@CZStatisticsProvider.apk@classes.dex\n" +
            "rm -rf /data/dalvik-cache/x86_64/system@priv-app@CZSystemUpdate@CZSystemUpdate.apk@classes.art\n" +
            "rm -rf /data/dalvik-cache/x86_64/system@priv-app@CZSystemUpdate@CZSystemUpdate.apk@classes.dex\n" +
            "rm -rf /data/dalvik-cache/x86_64/system@priv-app@GmsCore@GmsCore.apk@classes.dex\n" +
            "rm -rf /data/dalvik-cache/x86_64/system@priv-app@GmsCoreSetup@GmsCoreSetup.apk@classes.art\n" +
            "rm -rf /data/dalvik-cache/x86_64/system@priv-app@GmsCoreSetup@GmsCoreSetup.apk@classes.dex\n" +
            "rm -rf /data/dalvik-cache/x86_64/system@priv-app@Phonesky@Phonesky.apk@classes.art\n" +
            "rm -rf /data/dalvik-cache/x86_64/system@priv-app@Phonesky@Phonesky.apk@classes.dex\n" +
            "rm -rf /system/priv-app/CZNoviceHelp\n" +
            "rm -rf /system/priv-app/CZSetupWizard\n" +
            "rm -rf /system/priv-app/CZSystemUpdate\n" +
            "rm -rf /system/priv-app/GmsCore\n" +
            "rm -rf /system/priv-app/GmsCoreSetup\n" +
            "rm -rf /system/priv-app/Phonesky\n" +
            "rm -rf /system/priv-app/CZNoviceHelp\n" +
            "rm -rf /system/app/CZFeedback\n" +
            "rm -rf /system/app/CZRecommended\n" +
            "rm -rf /system/priv-app/GoogleFeedback\n" +
            "rm -rf /system/app/CZTextEditor\n" +
            "rm -rf /system/app/CZVoiceRecorder\n" +
            "rm -rf /system/app/Email\n" +
            "rm -rf /system/app/PandaNES\n" +
            "rm -rf /system/app/FileManager\n" +
            "rm -rf /system/app/PhoenixOneForx86\n" +
            "rm -rf /system/app/StardustBrowser_pad\n" +
            "rm -rf /system/phoenixos\n" +
            "11111111111111111111111111111111111111111111\n" +
            "rm -rf /data/data/com.chaozhuo.filemanager.phoenixos\n" +
            "rm -rf /init.android_x86.rc\n" +
            "rm -rf /charger\n" +
            "rm -rf /default.prop\n" +
            "rm -rf /file_contexts\n" +
            "rm -rf /fstab.android_x86\n" +
            "rm -rf /init\n" +
            "rm -rf /init.android_x86.rc\n" +
            "rm -rf /init.environ.rc\n" +
            "rm -rf /init.rc\n" +
            "rm -rf /init.superuser.rc\n" +
            "rm -rf /init.trace.rc\n" +
            "rm -rf /seapp_contexts\n" +
            "rm -rf /init.usb.rc\n" +
            "rm -rf /init.zygote32.rc\n" +
            "rm -rf /property_contexts\n" +
            "rm -rf /selinux_version\n" +
            "rm -rf /sepolicy\n" +
            "rm -rf /service_contexts\n" +
            "rm -rf /ueventd.android_x86.rc\n" +
            "rm -rf /ueventd.rc\n" +
            "rm -rf /init.android_x86_64.rc\n" +
            "rm -rf /fstab.android_x86_64\n" +
            "rm -rf /ueventd.android_x86_64.rc\n" +
            "rm -rf /data/backup/pending\n" +
            "rm -rf /data/data/com.android.email\n" +
            "rm -rf /data/data/com.android.vending\n" +
            "rm -rf /data/data/com.chaozhuo.browser.x86\n" +
            "rm -rf /data/data/com.chaozhuo.feedback\n" +
            "rm -rf /data/data/com.chaozhuo.filemanager.phoenixos\n" +
            "rm -rf /data/data/com.chaozhuo.novicehelp\n" +
            "rm -rf /data/data/com.chaozhuo.phoenixonelauncher.x86\n" +
            "rm -rf /data/data/com.chaozhuo.recommendedapp\n" +
            "rm -rf /data/data/com.chaozhuo.setupwizard\n" +
            "rm -rf /data/data/com.chaozhuo.texteditor.phoenixos\n" +
            "rm -rf /data/data/com.chaozhuo.update\n" +
            "rm -rf /data/data/com.chaozhuo.voicerecorder\n" +
            "rm -rf /data/data/com.google.android.gms\n" +
            "rm -rf /data/data/com.google.android.gms.setup\n" +
            "rm -rf /data/data/com.qiyi.video.pad\n" +
            "rm -rf /data/media/0/Android/data/com.chaozhuo.browser.x86\n" +
            "rm -rf /data/media/0/Android/data/com.chaozhuo.filemanager.phoenixos\n" +
            "rm -rf /data/media/0/Android/data/com.chaozhuo.phoenixonelauncher.x86\n" +
            "rm -rf /data/media/0/Android/data/com.chaozhuo.provider.statistics\n" +
            "rm -rf /data/media/0/Android/data/com.chaozhuo.recommendedapp\n" +
            "rm -rf /data/media/0/Android/data/com.google.android.gms\n" +
            "rm -rf /data/misc/profiles/cur/0/com.android.email\n" +
            "rm -rf /data/misc/profiles/cur/0/com.android.vending\n" +
            "rm -rf /data/misc/profiles/cur/0/com.chaozhuo.novicehelp\n" +
            "rm -rf /data/misc/profiles/cur/0/com.chaozhuo.phoenixonelauncher.x86\n" +
            "rm -rf /data/misc/profiles/cur/0/com.chaozhuo.recommendedapp\n" +
            "rm -rf /data/misc/profiles/cur/0/com.chaozhuo.texteditor.phoenixos\n" +
            "rm -rf /data/misc/profiles/cur/0/com.google.android.gms\n" +
            "rm -rf /data/misc/profiles/cur/0/com.google.android.gms.setup\n" +
            "rm -rf /data/misc/profiles/ref/com.android.email\n" +
            "rm -rf /data/misc/profiles/ref/com.android.vending\n" +
            "rm -rf /data/misc/profiles/ref/com.chaozhuo.novicehelp\n" +
            "rm -rf /data/misc/profiles/ref/com.chaozhuo.phoenixonelauncher.x86\n" +
            "rm -rf /data/misc/profiles/ref/com.chaozhuo.recommendedapp\n" +
            "rm -rf /data/misc/profiles/ref/com.chaozhuo.texteditor.phoenixos\n" +
            "rm -rf /data/misc/profiles/ref/com.google.android.gms\n" +
            "rm -rf /data/misc/profiles/ref/com.google.android.gms.setup\n" +
            "rm -rf /data/user_de/0/com.android.email\n" +
            "rm -rf /data/user_de/0/com.android.vending\n" +
            "rm -rf /data/user_de/0/com.chaozhuo.novicehelp\n" +
            "rm -rf /data/user_de/0/com.chaozhuo.phoenixonelauncher.x86\n" +
            "rm -rf /data/user_de/0/com.chaozhuo.recommendedapp\n" +
            "rm -rf /data/user_de/0/com.chaozhuo.texteditor.phoenixos\n" +
            "rm -rf /data/user_de/0/com.google.android.gms\n" +
            "rm -rf /data/user_de/0/com.google.android.gms.setup\n" +
            "rm -rf /data/system/chaozhuo\n" +
            "22222222222222222222222222222222222222222222222222222222222222222\n" +
            "rm -rf /data/data/com.chaozhuo.filemanager.phoenixos\n" +
            "rm -rf /init.android_x86.rc\n" +
            "rm -rf /charger\n" +
            "rm -rf /default.prop\n" +
            "rm -rf /file_contexts\n" +
            "rm -rf /fstab.android_x86\n" +
            "rm -rf /init\n" +
            "rm -rf /init.android_x86.rc\n" +
            "rm -rf /init.environ.rc\n" +
            "rm -rf /init.rc\n" +
            "rm -rf /init.superuser.rc\n" +
            "rm -rf /init.trace.rc\n" +
            "rm -rf /seapp_contexts\n" +
            "rm -rf /init.usb.rc\n" +
            "rm -rf /init.zygote32.rc\n" +
            "rm -rf /property_contexts\n" +
            "rm -rf /selinux_version\n" +
            "rm -rf /sepolicy\n" +
            "rm -rf /service_contexts\n" +
            "rm -rf /ueventd.android_x86.rc\n" +
            "rm -rf /ueventd.rc\n" +
            "rm -rf /init.android_x86_64.rc\n" +
            "rm -rf /fstab.android_x86_64\n" +
            "rm -rf /ueventd.android_x86_64.rc\n" +
            "rm -rf /data/backup/pending\n" +
            "rm -rf /data/data/com.android.email\n" +
            "rm -rf /data/data/com.android.vending\n" +
            "rm -rf /data/data/com.chaozhuo.browser.x86\n" +
            "rm -rf /data/data/com.chaozhuo.feedback\n" +
            "rm -rf /data/data/com.chaozhuo.filemanager.phoenixos\n" +
            "rm -rf /data/data/com.chaozhuo.novicehelp\n" +
            "rm -rf /data/data/com.chaozhuo.phoenixonelauncher.x86\n" +
            "rm -rf /data/data/com.chaozhuo.recommendedapp\n" +
            "rm -rf /data/data/com.chaozhuo.setupwizard\n" +
            "rm -rf /data/data/com.chaozhuo.texteditor.phoenixos\n" +
            "rm -rf /data/data/com.chaozhuo.update\n" +
            "rm -rf /data/data/com.chaozhuo.voicerecorder\n" +
            "rm -rf /data/data/com.google.android.gms\n" +
            "rm -rf /data/data/com.google.android.gms.setup\n" +
            "rm -rf /data/media/0/Android/data/com.chaozhuo.filemanager.phoenixos\n" +
            "rm -rf /data/media/0/Android/data/com.chaozhuo.phoenixonelauncher.x86\n" +
            "rm -rf /data/media/0/Android/data/com.chaozhuo.provider.statistics\n" +
            "rm -rf /data/media/0/Android/data/com.chaozhuo.recommendedapp\n" +
            "rm -rf /data/media/0/Android/data/com.google.android.gms\n" +
            "rm -rf /data/misc/profiles/cur/0/com.android.email\n" +
            "rm -rf /data/misc/profiles/cur/0/com.android.vending\n" +
            "rm -rf /data/misc/profiles/cur/0/com.chaozhuo.novicehelp\n" +
            "rm -rf /data/misc/profiles/cur/0/com.chaozhuo.phoenixonelauncher.x86\n" +
            "rm -rf /data/misc/profiles/cur/0/com.chaozhuo.recommendedapp\n" +
            "rm -rf /data/misc/profiles/cur/0/com.chaozhuo.texteditor.phoenixos\n" +
            "rm -rf /data/misc/profiles/cur/0/com.google.android.gms\n" +
            "rm -rf /data/misc/profiles/cur/0/com.google.android.gms.setup\n" +
            "rm -rf /data/misc/profiles/ref/com.android.email\n" +
            "rm -rf /data/misc/profiles/ref/com.android.vending\n" +
            "rm -rf /data/misc/profiles/ref/com.chaozhuo.novicehelp\n" +
            "rm -rf /data/misc/profiles/ref/com.chaozhuo.phoenixonelauncher.x86\n" +
            "rm -rf /data/misc/profiles/ref/com.chaozhuo.recommendedapp\n" +
            "rm -rf /data/misc/profiles/ref/com.chaozhuo.texteditor.phoenixos\n" +
            "rm -rf /data/misc/profiles/ref/com.google.android.gms\n" +
            "rm -rf /data/misc/profiles/ref/com.google.android.gms.setup\n" +
            "rm -rf /data/user_de/0/com.android.email\n" +
            "rm -rf /data/user_de/0/com.android.vending\n" +
            "rm -rf /data/user_de/0/com.chaozhuo.novicehelp\n" +
            "rm -rf /data/user_de/0/com.chaozhuo.phoenixonelauncher.x86\n" +
            "rm -rf /data/user_de/0/com.chaozhuo.recommendedapp\n" +
            "rm -rf /data/user_de/0/com.chaozhuo.texteditor.phoenixos\n" +
            "rm -rf /data/user_de/0/com.google.android.gms.setup\n" +
            "mv /system/lib/libhoudini.so /system/lib/QIY.so\n" +
            "mv /system/lib64/libhoudini.so /system/lib64/QIY.so\n" +
            "mv /system/lib/egl /system/lib/egl0\n" +
            "mv /system/lib64/egl /system/lib64/egl0\n" +
            "mv /system/lib/arm /system/lib/arm0\n" +
            "mv /system/lib64/arm64 /system/lib64/arm0\n" +
            "mv /system/lib/hw/audio.primary.x86.so /system/lib/hw/audio.primary.x860.so\n" +
            "mv /system/lib/hw/camera.x86.so /system/lib/hw/camera.x860.so\n" +
            "mv /system/lib/hw/power.x86.so /system/lib/hw/power.x860.so\n" +
            "mv /system/lib/libclcore_x86.bc /system/lib/libclcore_x860.bc\n" +
            "mv /system/lib/modules /system/lib/modules0\n" +
            "mv /system/lib64/hw/audio.primary.x86.so /system/lib64/hw/audio.primary.x860.so\n" +
            "mv /system/lib64/hw/camera.x86.so /system/lib64/hw/camera.x860.so\n" +
            "mv /system/lib64/hw/power.x86.so /system/lib64/hw/power.x860.so\n" +
            "mv /system/lib64/libclcore_x86.bc /system/lib64/libclcore_x860.bc\n" +
            "mv /system/lib/fastpipe.ko /system/lib/fastpipe0.ko\n" +
            "mv /system/lib/libclcore_x86.bc /system/lib/libclcore_x860.bc\n" +
            "mv /system/lib/libfastpipe.so /system/lib/libfastpipe0.so\n" +
            "mv /system/lib/libFFmpegExtractor.so /system/lib/libFFmpegExtractor0.so\n" +
            "mv /system/lib/libfuse-lite.so /system/lib/libfuse-lite0.so\n" +
            "mv /system/lib/libGLESv3.so /system/lib/libGLESv30.so\n" +
            "mv /system/lib/libglib.so /system/lib/libglib0.so\n" +
            "mv /system/lib/libldutils.so /system/lib/libldutils0.so\n" +
            "mv /system/lib/libnb.so /system/lib/libnb0.so\n" +
            "mv /system/lib/libntfs-3g.so /system/lib/libntfs-3g0.so\n" +
            "mv /system/lib/libOpenglSystemCommon.so /system/lib/libOpenglSystemCommon0.so\n" +
            "mv /system/lib/libsbc.so /system/lib/libsbc0.so\n" +
            "mv /system/lib/libstagefright_soft_eglenc.so /system/lib/libstagefright_soft_eglenc0.so\n" +
            "mv /system/lib/libstagefright_soft_ffmpegadec.so /system/lib/libstagefright_soft_ffmpegadec0.so\n" +
            "mv /system/lib/libstagefright_soft_gl1enc.so /system/lib/libstagefright_soft_gl1enc0.so\n" +
            "mv /system/lib/libstagefright_soft_gl2enc.so /system/lib/libstagefright_soft_gl2enc0.so\n" +
            "mv /system/etc/.has_su_daemon /system/etc/.has_su_daemon0\n" +
            "mv /system/etc/app_arch_list /system/etc/app_arch_list0\n" +
            "mv /system/etc/cell.data /system/etc/cell.data0\n" +
            "mv /system/etc/excluded-input-devices.xml /system/etc/excluded-input-devices0.xml\n" +
            "mv /system/etc/gl_force /system/etc/gl_force0\n" +
            "mv /system/etc/init.sh /system/etc/init.sh0\n" +
            "mv /system/etc/media_codecs_google_video.xml /system/etc/media_codecs_google_video.xml0\n" +
            "mv /system/etc/modify-id /system/etc/modify-id0\n" +
            "mv /system/etc/modules.blacklist /system/etc/modules.blacklist0\n" +
            "mv /system/etc/tiantang2 /system/etc/tiantang20\n" +
            "\n" +
            "\n";

}
